sdk: "/Users/lucascampbell-rossen/.rvm/gems/ruby-1.9.3-p448/gems/rhodes-4.0.0"
sdkversion: 4.0.0
name: RhoGallery Mobile
version: 1.0
vendor: rhomobile
build: debug
bbver: 6.0
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator7.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhogallery.new
  BundleURLScheme: rhogallery-mobile
wp:
  productid: '86e2e620-0799-0131-ea8a-60f8470f025a'
symbian:
  uid: '0xe5b5bf80'
android:
  version: 4.1.2

extensions: ["rhoconnect-client",'digest','digest-md5','mspec','fileutils']
  
capabilities:
- non_motorola_device